version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
  
  database:
    image: postgres:latest
    container_name: "postgres"
    environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=wasd
          - POSTGRES_DB=cc
    ports:
      - 7433:5432
          
  database_server:
    container_name: "database_server"
    build: ./database
    image: database
    ports:
      - 4000:4000
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 4000
      DATABASE_URL: postgresql://admin:wasd@database:5432/cc

    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- npx prisma generate && npx prisma migrate deploy && node db.js'
    
  consumer1:
    build: ./consumer/
    image: consumer
    container_name: "Salman_Bhai"
    ports:
      - 7500:7500
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 7500
      NAME: Salman_Khan
      PRODUCER: producer

      
    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- node consumer.js'
  
  consumer2:
    image: consumer
    container_name: "Binod"
    ports:
      - 7501:7501
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 7501
      NAME: Binod
      PRODUCER: producer
      
    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- node consumer.js'
  producer:
    build: ./producer
    container_name: "producer"
    image: producer
    ports:
      - 6969:6969
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 6969
    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- node producer.js'
  frontend:
    image: frontend
    container_name: "frontend"
    build: ./frontend
    logging:
      driver: none
    ports:
      - 3000:3000
    depends_on:
      - "database_server"
    environment:
      PRODUCER: producer
      DATABASE: database_server
